
# blacklist
branches:
  except:
    - road_racing_rewrite

notifications:
  email: false

sudo: false
addons:
  apt:
    packages:
      - python-virtualenv
      - ncftp
      - dvipng # TODO: do we need this?
      - lmodern
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-extra-utils # texfot

install:
    # - sudo add-apt-repository ppa:texlive-backports/ppa -y
    # - sudo apt-get update -y
    # - sudo apt-get install texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra latexmk texlive-science -y
    # - sudo apt-get install ncftp -y
    # - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    # - tar -zxvf install-tl-unx.tar.gz
    # - cd install-tl-*
    # - sudo ./install-tl --profile="$TRAVIS_BUILD_DIR/latex.profile"
    # - export PATH=$PATH:/usr/local/texlive/CURRENT/bin/x86_64-linux
    # - cd $TRAVIS_BUILD_DIR

    - scripts/install.sh
    - export PATH=$PATH:$HOME/local/latexdiff/bin:$HOME/rcs-latexdiff/venv/bin

cache: apt

script:
  - scripts/main.sh

after_success:
  - scripts/after-success.sh

env:
  global:
    - secure: "QFpLp44tE6qATEu0AMjzGS3Kzh4jZDd7gCIKJK+d3cFYh47kHf95Ke0LUf1p6MPAIlfBvfIvCTpSxK5PoPeMnZjMVzhEKgP0zrEQDWU3kOMep5faM0lDwzCcxfbEN6nlMrLXp/x/XnbPGgrG0iWjtgoZfpWUX+BHDfHFacQnjcQ="
    - secure: "Rvoa5HPs7Vy070B0FnVGfE9kWZsRUJ+IGz5UtzeIOnEFllUEN77yDLz3AVJvLROhqLPOqSLCDOFngXhP5HJHeiz3tdVO6yAF4MVPBDSCWuc/J9bZu5wDN6cKqkQ5lgLXOXBYm9o30ShkvnoNWwobIknoiFLPB6XRlT6TJVd2FqM="
