sudo: false

# blacklist
branches:
  except:
    - road_racing_rewrite
notifications:
  email: false

addons:
  apt:
    packages:
      - python-virtualenv
      - ncftp
      - dvipng # TODO: do we need this?
      - lmodern
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra

install:
  - ./scripts/install.sh

script:
  - ./scripts/main.sh

after_success:
  - ./scripts/after-success.sh

env:
  global:
    - secure: "QFpLp44tE6qATEu0AMjzGS3Kzh4jZDd7gCIKJK+d3cFYh47kHf95Ke0LUf1p6MPAIlfBvfIvCTpSxK5PoPeMnZjMVzhEKgP0zrEQDWU3kOMep5faM0lDwzCcxfbEN6nlMrLXp/x/XnbPGgrG0iWjtgoZfpWUX+BHDfHFacQnjcQ="
    - secure: "Rvoa5HPs7Vy070B0FnVGfE9kWZsRUJ+IGz5UtzeIOnEFllUEN77yDLz3AVJvLROhqLPOqSLCDOFngXhP5HJHeiz3tdVO6yAF4MVPBDSCWuc/J9bZu5wDN6cKqkQ5lgLXOXBYm9o30ShkvnoNWwobIknoiFLPB6XRlT6TJVd2FqM="
